import type { AgentState, WorkspaceId, WorkflowNode } from "./types";

export const workspaces: Array<{
  id: WorkspaceId;
  label: string;
  eyebrow: string;
  description: string;
}> = [
  {
    id: "intake",
    label: "Intake",
    eyebrow: "00 idea ingestion",
    description: "Capture the raw product concept and initialize the validation graph.",
  },
  {
    id: "strategy",
    label: "Strategy",
    eyebrow: "01 market validation",
    description: "Evaluate market pressure, competitors, personas, assumptions, and risks.",
  },
  {
    id: "prd",
    label: "PRD Generation",
    eyebrow: "02 requirement synthesis",
    description: "Transform validation evidence into a focused MVP requirements draft.",
  },
  {
    id: "synthesis",
    label: "Synthesis",
    eyebrow: "03 build decision",
    description: "Produce a pursue, refine, or reject recommendation with evidence.",
  },
  {
    id: "deployment",
    label: "Deployment",
    eyebrow: "04 execution readiness",
    description: "Assess MVP scope, implementation risk, stack fit, and readiness.",
  },
  {
    id: "launch",
    label: "Launch",
    eyebrow: "05 final package",
    description: "Package validation evidence, next actions, and static MVP export.",
  },
];

export const initialAgents: AgentState[] = [
  ["supervisor", "Workflow Supervisor Agent", "Routes stages, retries, dependencies, and graph transitions."],
  ["memory", "Memory Agent", "Maintains project context, artifact lineage, and decisions."],
  ["prompt-architect", "Prompt Architect Agent", "Turns rough ideas into structured execution prompts."],
  ["prompt-validator", "Prompt Validator Agent", "Critiques prompts for clarity, constraints, and output contract quality."],
  ["refinement", "Refinement Agent", "Clarifies problem, audience, value proposition, and assumptions."],
  ["market-research", "Market Research Agent", "Collects market signals and demand evidence."],
  ["competitor-analysis", "Competitor Analysis Agent", "Maps alternatives, saturation, and positioning gaps."],
  ["persona-validation", "Persona Validation Agent", "Simulates customer and stakeholder reactions."],
  ["prd", "PRD Agent", "Generates product requirements and acceptance criteria."],
  ["prd-reviewer", "PRD Reviewer Agent", "Checks PRD completeness, acceptance criteria, and implementation detail."],
  ["ux-ui", "UX/UI Agent", "Converts requirements into flow and interface implications."],
  ["interface-improvement", "Interface Improvement Agent", "Reviews workflow clarity, hierarchy, copy, and validation visibility."],
  ["gpt-image", "GPT Image Agent", "Creates prototype imagery or labelled visual prompt fallback cards."],
  ["prototype-review", "Prototype Review Agent", "Holds prototype approval before build preparation starts."],
  ["designer", "Designer Agent", "Validates layout quality, readability, spacing, and visual coherence."],
  ["stitch-design", "Stitch Design Agent", "Represents design iteration and UI concept handoffs."],
  ["architecture", "Architecture Agent", "Defines stack direction and implementation risk."],
  ["mvp-planning", "MVP Planning Agent", "Creates MVP backlog, scope cuts, and execution sequence."],
  ["qa-critic", "QA Critic Agent", "Critiques ambiguity, feasibility, and validation gaps."],
  ["build-orchestrator", "Build Orchestrator Agent", "Unlocks implementation planning after prototype approval."],
  ["launch", "Launch Agent", "Packages launch narrative, readiness, and next actions."],
].map(([role, name, description], index) => ({
  id: String(role),
  role: role as AgentState["role"],
  name: String(name),
  description: String(description),
  status: index === 0 ? "queued" : "idle",
  currentTask: index === 0 ? "Awaiting idea intake" : "Standing by for graph routing",
  progress: 0,
  outputArtifactIds: [],
  dependencyArtifactIds: [],
  lastActivityAt: new Date().toISOString(),
}));

export const initialNodes: WorkflowNode[] = [
  {
    id: "intake",
    stage: "Prompt lifecycle",
    label: "Intake",
    status: "queued",
    assignedAgentId: "refinement",
    dependencyNodeIds: [],
    requiredArtifactTypes: ["data-assumption", "prompt", "prompt-review"],
    validationCriteria: [
      "Rough idea is non-empty",
      "Crafted prompt includes target user, pain hypothesis, constraints, and output contract",
      "Prompt validation score is visible before Strategy",
    ],
    outputArtifactIds: [],
    retryCount: 0,
    maxRetries: 1,
    nextNodeIds: ["strategy"],
  },
  {
    id: "strategy",
    stage: "Market validation",
    label: "Strategy",
    status: "waiting",
    assignedAgentId: "market-research",
    dependencyNodeIds: ["intake"],
    requiredArtifactTypes: ["market-insight", "competitor-analysis", "persona", "data-assumption"],
    validationCriteria: [
      "Market leads include pain signal, rationale, validation question, confidence, and source",
      "Competitor and persona artifacts are generated",
      "Fallback or OpenAI evidence source is labelled",
    ],
    outputArtifactIds: [],
    retryCount: 0,
    maxRetries: 2,
    nextNodeIds: ["prd"],
  },
  {
    id: "prd",
    stage: "Requirements generation",
    label: "PRD Generation",
    status: "waiting",
    assignedAgentId: "prd",
    dependencyNodeIds: ["strategy"],
    requiredArtifactTypes: ["prd", "prd-review", "ux-flow"],
    validationCriteria: [
      "PRD contains required startup-quality sections",
      "PRD review reports completeness and ambiguity findings",
      "Market evidence and persona objections affect scope",
    ],
    outputArtifactIds: [],
    retryCount: 0,
    maxRetries: 1,
    nextNodeIds: ["synthesis"],
  },
  {
    id: "synthesis",
    stage: "Review and hold",
    label: "Synthesis",
    status: "waiting",
    assignedAgentId: "qa-critic",
    dependencyNodeIds: ["prd"],
    requiredArtifactTypes: ["synthesis-plan", "interface-review", "qa-critique", "mvp-plan"],
    validationCriteria: [
      "Upstream artifacts are reviewed before recommendation",
      "Interface improvement scores and checklist are visible",
      "Workflow holds until approve, revise, or rerun",
    ],
    outputArtifactIds: [],
    retryCount: 0,
    maxRetries: 1,
    nextNodeIds: ["deployment", "prd", "intake"],
  },
  {
    id: "deployment",
    stage: "Prototype review",
    label: "Deployment",
    status: "waiting",
    assignedAgentId: "architecture",
    dependencyNodeIds: ["synthesis"],
    requiredArtifactTypes: ["architecture", "prototype"],
    validationCriteria: [
      "Prototype direction is generated or labelled fallback",
      "Prototype approval is pending before Launch",
      "Rejection exposes regeneration path",
    ],
    outputArtifactIds: [],
    retryCount: 0,
    maxRetries: 1,
    nextNodeIds: ["launch", "synthesis"],
  },
  {
    id: "launch",
    stage: "Approved package",
    label: "Launch",
    status: "waiting",
    assignedAgentId: "launch",
    dependencyNodeIds: ["deployment"],
    requiredArtifactTypes: ["implementation-plan", "design-validation", "launch-plan"],
    validationCriteria: [
      "Prototype approval exists before build-preparation outputs",
      "Design Validation Report is approved",
      "Static export contains full MVP Foundation Package",
    ],
    outputArtifactIds: [],
    retryCount: 0,
    maxRetries: 1,
    nextNodeIds: [],
  },
];
